package org.se.lab;

// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class TranslatePOTest
{
    private WebDriver driver;

    @Before
    public void setUp()
    {
        driver = new FirefoxDriver();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void translate_CatIntoFrancais()
    {
        TranslatorPO translator = new TranslatorPO(driver);
        translator.setWord("cat");
        translator.setLang(Language.FRANCAIS);
        ResultPO result = translator.translate();
        String text = result.getText();
        Assert.assertEquals("Translate: cat into Chatte", text);
    }

    @Test
    public void translate_CatIntoDeutsch()
    {
        TranslatorPO translator = new TranslatorPO(driver);
        translator.setWord("cat");
        translator.setLang(Language.DEUTSCH);
        ResultPO result = translator.translate();
        String text = result.getText();
        Assert.assertEquals("Translate: cat into Katze", text);
    }
}
