SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CREDIT_CARD;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PHONE;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS RESERVATION_CUSTOMER;
DROP TABLE IF EXISTS hibernate_sequence;
SET FOREIGN_KEY_CHECKS = 1;
